[package]
name = "digital_asset_launchpad"
version = "1.0.0"
authors = []

[addresses]
launchpad_addr = "0x5be4aa46852694bf8a5d78dc34546a9f376986814b9d2f00bc12d5d3c48a8002"
initial_creator_addr = "0x5be4aa46852694bf8a5d78dc34546a9f376986814b9d2f00bc12d5d3c48a8002"
minter = "0x00e18a6040d3d56e54f63b82358125949ecf23a70a897c897f04bb25d61a175d"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token-objects" }
TokenMinter = { git = "https://github.com/aptos-labs/token-minter.git", rev = "main", subdir = "token-minter" }

[dev-dependencies]
